### ISSUE TITLE
图片太相似时,得出的结果是同一张图片跟一张图片相似

### ISSUE THREAD

**Issue by aajron** [amazingTest/Pic-Diff-Recognizer#1]

**Comment by amazingTest** [comment]
是的，但2张图片意义是不一样的。一个是录制的baseline（测试用例的预期）一个是实时当下测试得到的图片（测试用例的实际结果）。如果相似度高，证明测试通过。程序找到了预期的图片。

**Comment by aajron** [comment]
第一个问题:baseline 录制了43张图片，screenshot 43张图片跟  base line进行对比，最后得到的结果是baseline 第一张跟 screenshot的第二/第三张相似，预期结果应该是baseline第一张跟screenshot第一张相似，baseline 第二张 跟screenshot 第二张相似。主要原因是两张最相似的图片的mean_squared_error_result函数得出的值不一定是最小
第二个问题:js 在获取窗口大小的时候好像每次都比原来的window小了，导致图片第二次以及接下来的截图中越来越窄
