### ISSUE TITLE
第一个问题:baseline 录制了43张图片，screenshot 43张图片跟  base line进行对比，最后得到的结果是baseline 第一张跟 screenshot的第二/第三张相似，预期结果应该是baseline第一张跟screenshot第一张相似，baseline 第二张 跟screenshot 第二张相似。主要原因是两张最相似的图片的mean_squared_error_result函数得出的值不一定是最小

### ISSUE THREAD

**Issue by aajron** [amazingTest/Pic-Diff-Recognizer#2]
第一个问题:baseline 录制了43张图片，screenshot 43张图片跟  base line进行对比，最后得到的结果是baseline 第一张跟 screenshot的第二/第三张相似，预期结果应该是baseline第一张跟screenshot第一张相似，baseline 第二张 跟screenshot 第二张相似。主要原因是两张最相似的图片的mean_squared_error_result函数得出的值不一定是最小
第二个问题:js 在获取窗口大小的时候好像每次都比原来的window小了，导致图片第二次以及接下来的截图中越来越窄

_Originally posted by @aajron in https://github.com/amazingTest/Pic-Diff-Recognizer/issues/1#issuecomment-688646967_

**Comment by amazingTest** [comment]
第一个问题：相似算法就是比谁mean_squared_error最小，他最小就代表算法承认他是最相似。用这个算法作为初步筛选是因为他速度最快。
第二个问题：这个问题具体怎么复现可以说下吗，我实践中没有发现

**Comment by aajron** [comment]
窗口大小主要是selenium的set_window_size和js 的return document.documentElement.scrollWidth差了竖向滚动条+一个边边。例如屏幕大小1024，window size 1024, document.documentElement.scrollWidth 第一次 = 991， 滚动条 = 19，还有一点边边 = 14

**Comment by amazingTest** [comment]
是这样，我在实现过程中可能也遇到了这个问题，没有太深究，感谢反馈，能提pr修复就更好了 😄 @aajron

**Comment by aajron** [comment]
目前我的做法是有竖向滚动条的时候，就固定浏览器一个宽度不变，只改变高度。有个建议：第二遍截图时，最好重新实例化driver，保证跟第一遍的操作一致（主要防止宽高的问题）
